api/urls.py
from __future__ import unicode_literals

from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import DefaultRouter

from django.conf.urls import url, include

from . import views


router = DefaultRouter()
router.register(r'forms', views.FormViewSet)
router.register(r'responses', views.FormResponseViewSet)
router.register(r'files', views.ResponseFileViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api-token-auth/', obtain_auth_token)
]

forms/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/', include('api.urls')),
    url(r'^', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

web/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views


urlpatterns = [
    url(r'^$',
        views.FormList.as_view(), name='form.list'),

    url(r'^formulario/nuevo$',
        views.FormCreate.as_view(), name='form.create'),

    url(r'^formulario/(?P<pk>[0-9]+)$',
        views.FormDetail.as_view(), name='form.detail'),

    url(r'^formulario/(?P<pk>[0-9]+)/editar$',
        views.FormEdit.as_view(), name='form.edit'),

    url(r'^formulario/(?P<pk>[0-9]+)/borrar$',
        views.FormDelete.as_view(), name='form.delete'),

    url(r'^formulario/(?P<pk>[0-9]+)/registros',
        views.ResponseList.as_view(), name='response.list'),

    url(r'^formulario/(?P<form_pk>[0-9]+)/registro/(?P<pk>[0-9]+)$',
        views.ResponseDetail.as_view(), name='response.detail'),

    url(r'^accounts/login/$', login, {'template_name': 'admin/login.html'}),
    url(r'^accounts/logout/$', logout),
]

api/models.py
from __future__ import unicode_literals

from model_utils import Choices
from model_utils.fields import StatusField
from model_utils.models import TimeStampedModel

from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class Form(TimeStampedModel):
    QUESTION_TYPES = (
        ('header', _('Header')),
        ('text', _('Text')),
        ('list', _('List')),
        ('table', _('Table')),
        ('file', _('File')),
        ('related', _('Related Form'))
    )

    COLUMN_TYPES = (
        ('text', _('Text')),
        ('list', _('List')),
        ('radio', _('Radio')),
        ('checkbox', _('Checkbox'))
    )

    FORM_STATUS = Choices(
        ('editable', _('Editable')),
        ('active', _('Active')),
        ('closed', _('Closed'))
    )

    name = models.CharField(_('name'), max_length=255)
    description = models.TextField(_('description'))
    status = StatusField(_('status'), choices_name='FORM_STATUS')
    user = models.ForeignKey(User, verbose_name=_('user'))

    contents = JSONField(_('contents'))

    class Meta:
        verbose_name = _('form')
        verbose_name_plural = _('forms')

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class FormResponse(TimeStampedModel):
    form = models.ForeignKey(Form, verbose_name=_('form'))
    user = models.ForeignKey(User, verbose_name=_('user'))

    class Meta:
        verbose_name = _('form response')
        verbose_name_plural = _('form responses')

    def answers(self):
        return self.response_set.order_by('code')

    def __str__(self):
        return '%s - %s' % (self.form.name, self.user.username)


@python_2_unicode_compatible
class Response(models.Model):
    code = models.CharField(_('code'), max_length=10)
    question = models.CharField(_('question'), max_length=255)
    answer = models.CharField(_('answer'), max_length=255, blank=True)
    label = models.CharField(_('label'), max_length=255, blank=True)
    related = models.BooleanField(_('realted'), default=False)

    form_response = models.ForeignKey(FormResponse, verbose_name=_('form response'))

    class Meta:
        verbose_name = _('response')
        verbose_name_plural = _('responses')

    def __str__(self):
        return self.answer


class ResponseFile(models.Model):
    file = models.FileField(verbose_name=_('file'))
    response = models.ForeignKey(Response, verbose_name=_('response'))

    class Meta:
        verbose_name = _('file')
        verbose_name_plural = _('files')

forms/wsgi.py
import os

from django.core.wsgi import get_wsgi_application

application = get_wsgi_application()

api/views.py
from __future__ import unicode_literals

from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter
from rest_framework import viewsets, permissions
from rest_framework.decorators import list_route
from rest_framework.response import Response

from . import models, serializers, filters


class FormViewSet(viewsets.ModelViewSet):
    queryset = models.Form.objects.all()
    serializer_class = serializers.FormSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    @list_route()
    def simple(self, request):
        forms = models.Form.objects.all()
        serializer = serializers.SimpleFormSerializer(forms, many=True)
        return Response(serializer.data)


class FormResponseViewSet(viewsets.ModelViewSet):
    queryset = models.FormResponse.objects.all()
    serializer_class = serializers.FormResponseSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    filter_backends = (SearchFilter, DjangoFilterBackend)
    filter_class = filters.FormResponseFilter
    search_fields = ('response__answer',)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class ResponseFileViewSet(viewsets.ModelViewSet):
    queryset = models.ResponseFile.objects.all()
    serializer_class = serializers.ResponseFileSerializer

    def pre_save(self, obj):
        obj.file = self.request.FILES.get('file')

web/views.py
from __future__ import unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, DetailView, DeleteView

from api import models


class FormList(LoginRequiredMixin, ListView):
    template_name = 'web/form_list.html'
    context_object_name = 'forms'

    def get_queryset(self):
        return models.Form.objects.order_by('-created')


class FormCreate(LoginRequiredMixin, TemplateView):
    template_name = 'web/form_builder.html'


class FormDetail(LoginRequiredMixin, DetailView):
    model = models.Form
    context_object_name = 'form'
    template_name = 'web/form_detail.html'


class FormEdit(LoginRequiredMixin, DetailView):
    model = models.Form
    context_object_name = 'form'
    template_name = 'web/form_builder.html'


class FormDelete(LoginRequiredMixin, DeleteView):
    model = models.Form
    context_object_name = 'form'
    template_name = 'web/form_delete.html'
    success_url = reverse_lazy('form.list')


class ResponseList(LoginRequiredMixin, ListView):
    template_name = 'web/response_list.html'
    context_object_name = 'responses'

    def get_queryset(self):
        return models.FormResponse.objects.filter(
            form_id=self.kwargs.get("pk", None)
        ).order_by('-created')

    def get_context_data(self, **kwargs):
        context = super(ResponseList, self).get_context_data(**kwargs)
        form_response = models.FormResponse.objects.filter(form_id=self.kwargs.get("pk", None))[:1]
        context["headers"] = models.Response.objects.filter(
            form_response=form_response
        ).order_by('code')

        return context


class ResponseDetail(LoginRequiredMixin, DetailView):
    model = models.FormResponse
    context_object_name = 'response'
    template_name = 'web/response_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ResponseDetail, self).get_context_data(**kwargs)

        form_response_id = self.kwargs.get("pk", None)

        context["related"] = models.FormResponse.objects.filter(
            response__related=True, response__answer=form_response_id
        )

        return context

web/templates/web/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block meta %}
      <meta name="description" content="">
      <meta name="author" content="">
    {% endblock %}

    <title>{% block title %}Forms{% endblock %}</title>

    <link href="{% static 'web/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %}{% endblock %}

    {% block head %}{% endblock %}
  </head>

  <body>
    {% block navbar %}
      <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Forms</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
          </div>
        </div>
      </nav>
    {% endblock %}

    {% block content %}{% endblock %}

    {% block footer %}
      <div class="container">
        <div class="row footer">

        </div>
      </div>
    {% endblock %}

    {% block javascript %}{% endblock %}

  </body>
</html>

web/templates/web/form_builder.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% load render_bundle from webpack_loader %}

{% block content %}
  <div id="form-builder" class="center-block"></div>

  <script type="text/javascript">
    var form_id = {{ form.id | default:0 }};
  </script>

  {% render_bundle 'vendors' %}
  {% render_bundle 'builder' %}
{% endblock %}

web/templates/web/form_delete.html
{% extends 'web/base.html' %}

{% block content %}
  <div class="container">
    <div class="alert alert-warning" role="alert">
      <form action="" method="post">
        {% csrf_token %}
        <h3>¿Eliminar el formulario {{ form.name }}?</h3><br>
        <button class="btn btn-default" onclick="window.history.back()">Cancelar</button>
        <input class="btn btn-danger" type="submit" value="Confirmar" />
      </form>
    </div>
  </div>
{% endblock %}

web/templates/web/form_detail.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% load render_bundle from webpack_loader %}

{% block content %}
  <div id="form-response" class="center-block"></div>

  <script type="text/javascript">
    var form_id = {{ form.id | default:0 }};
  </script>

  {% render_bundle 'vendors' %}
  {% render_bundle 'response' %}
{% endblock %}

web/templates/web/form_list.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% load render_bundle from webpack_loader %}

{% block content %}
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-6">
            <h3 class="panel-title">Formularios</h3>
          </div>
          <div class="col-md-6">
            <a href="{% url 'form.create' %}" class="btn btn-primary pull-right">Nuevo formulario</a>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      {% for form in forms %}
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <span class="lead">{{ form.name }}
              {% if form.status == "editable" %}
                <small class="label label-success pull-right">
              {% elif form.status == "active" %}
                <small class="label label-primary float-right">
              {% elif form.status == "closed" %}
                <small class="label label-danger float-right">
              {% endif %}
                {{ form.get_status_display }}</small>
              </span>
            </div>
            <div class="panel-body">
              <h4><a href="{% url 'response.list' form.pk %}">Respuestas</a></h4>
              <span class="text-muted pull-left">
                Última modificación: {{ form.modified | date:"d/M/Y H:i"}}
              </span><br><br>
              <a href="{% url 'form.detail' form.pk %}">Ver</a>
              <a href="{% url 'form.edit' form.pk %}">Editar</a>
              <a href="{% url 'form.delete' form.pk %}">Eliminar</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

{% block css %}
  <link href="{% static 'web/css/app.css' %}" rel="stylesheet">
{% endblock %}

web/templates/web/form_view.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% load render_bundle from webpack_loader %}

{% block content %}
  <div id="form-response" class="center-block"></div>

  <script type="text/javascript">
    var form_id = {{ form.id | default:0 }};
  </script>

  {% render_bundle 'vendors' %}
  {% render_bundle 'response' %}
{% endblock %}

web/templates/web/response_detail.html
{% extends 'web/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-12">
            <h3 class="panel-title">Detalle del registro</h3>
          </div>
        </div>
      </div>
      <div class="panel-body details">
        <div class="row">
          <div class="col-md-3 text-right text-muted">
            <span>Fecha de registro:</span>
          </div>
          <div class="col-md-9">
            {{ response.created | date:"d/M/Y H:i" }}
          </div>
        </div>
        {% for answer in response.answers %}
          <div class="row">
            <div class="col-md-3 text-right text-muted">
              {{ answer.code }}. {{ answer.question }}
            </div>
            <div class="col-md-9">
              {% if answer.responsefile_set.all %}
                <div class="row">
                  {% for file in answer.responsefile_set.all %}
                    {% if answer.answer == "image" %}
                      <div class="col-md-4">
                        <a class="thumbnail" href="{{ file.file.url }}" target="_blank">
                          <img src="{{ file.file.url }}" class="img-responsive">
                        </a>
                      </div>
                    {% else %}
                      <div class="col-md-12">
                        <a href="{{ file.file.url }}" target="_blank">
                          <span class="glyphicon glyphicon-file">{{ file.file.name }}</span>
                        </a>
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
              {% elif answer.label %}
                <span>{{ answer.label }}</span>
              {%  else %}
                <span>{{ answer.answer }}</span>
              {%  endif %}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    {% if related %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-12">
              <h3 class="panel-title">Registros relacionados: {{ related.1.form.name }}</h3>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-12">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Fecha</th>
                  {% for answer in related.1.answers %}
                    <th>{{ answer.question }}</th>
                  {% endfor %}
                </tr>
              </thead>
              <tbody>
                {% for rel in related %}
                  <tr>
                    <td>
                      <a href="{% url 'response.detail' rel.form.pk rel.pk %}">
                        {{ rel.created | date:"d/M/Y H:i"}}
                      </a>
                    </td>
                    {% for answer in rel.answers %}
                      <td>
                        {% if answer.label %}
                          {{ answer.label }}
                        {%  else %}
                          {{ answer.answer }}
                        {%  endif %}
                      </td>
                    {% endfor %}
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

{% block css %}
  <link href="{% static 'web/css/app.css' %}" rel="stylesheet">
{% endblock %}

web/templates/web/response_list.html
{% extends 'web/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-6">
            <h3 class="panel-title">Respuestas del formulario</h3>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <h3>{{ responses.0.form.name }}</h3>
          </div>
        </div>
      </div>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Fecha</th>
            {% for header in headers %}
              <th>{{ header.question }}</th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {% for response in responses %}
            <tr>
              <td>
                <a href="{% url 'response.detail' response.form.pk response.pk %}">
                  {{ response.created | date:"d/M/Y H:i"}}
                </a>
              </td>
              {% for answer in response.answers %}
                <td>
                  {% if answer.label %}
                    {{ answer.label }}
                  {%  else %}
                    {{ answer.answer }}
                  {%  endif %}
                </td>
              {% endfor %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

{% block css %}
  <link href="{% static 'web/css/app.css' %}" rel="stylesheet">
{% endblock %}